### ISSUE TITLE
你好请问能分享一下这次比赛的数据集吗？

### ISSUE THREAD

**Issue by naniwet** [ultimatejoe/rul_of_cutter#1]
你好请问能分享一下这次比赛的数据吗 naniwet@163.com谢谢~
我在做实验，但是暂时没有现存的数据。谢谢！

**Comment by ultimatejoe** [comment]
您好，比赛数据过于庞大，我应该不会上传了。但是您可以关注一下PHM 2008年的火箭引擎比赛，它也是一个寿命预测类的比赛，而且提供了[NASA的火箭引擎数据集](https://github.com/tashrifbillah/Remaining-Useful-Life-Estimation-of-Rocket-Engines)。另外，PHM 2010的比赛也是刀具寿命预测的，但是我刚才看了一下它的官网，下载链接已经失效了。所以您在其他地方可以在找找看。
最后，附上一篇PHM比赛的回顾文章[A_Review_of_PHM_Data_Competitions_from_2008_to_2017](https://www.researchgate.net/publication/327872068_A_Review_of_PHM_Data_Competitions_from_2008_to_2017)，可能对您的研究有帮助。
